### ISSUE TITLE
feature request - hierarchical clustering of large sets of comparisons

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#1]
Enable generation of tile plot for full STRIPE-seq vs. RNA-seq untreated/diamide comparisons.

**Comment by rpolicastro** [comment]
Added with [latest commit](https://github.com/rpolicastro/tsrexplorer/commit/5252b4db64be9a83c50239e82b927e1e3616644f).

Documentation for example using TSSs can be seen [here](https://github.com/rpolicastro/tsrexplorer/commit/5252b4db64be9a83c50239e82b927e1e3616644f).
