### ISSUE TITLE
Error in quantiles for genome_distribution

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#10]
> tss_distribution <- genomic_distribution(exp, data_type = "tss", threshold = 3, quantiles = 5)
Error in x[!nas] : object of type 'closure' is not subsettable
In addition: Warning messages:
1: In is.na(x) : is.na() applied to non-(list or vector) of type 'closure'
2: In is.na(x) : is.na() applied to non-(list or vector) of type 'closure'

Also, ?genomic_distribution has a typo: rather than "quantiles: number of quantiles to break the data down into", it reads "number: of quantiles to break the data down into"

**Comment by rpolicastro** [comment]
This seems to work fine for me. Can you reproduce it?

**Comment by rpolicastro** [comment]
Looks like the problem resolved itself
