### ISSUE TITLE
TSS genomic distribution quantiles

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#11]
> p <- plot_genomic_distribution(genomic_dist) +
+ theme(text = element_text(size = 6))
Error in ggplot(genomic_distribution$genomic_distribution, aes(x = samples,  : 
  object 'genomic_dist' not found
> 
> ggsave("tss_genomic_distribution_quantiles.png", plot = p, device = "png", type = "cairo", height = 4, width = 4)
> tss_distribution <- genomic_distribution(exp, data_type = "tss", threshold = 3, quantiles = 5)
> 
> p <- plot_genomic_distribution(genomic_distribution) +
+ theme(text = element_text(size = 6))
Error: object of type 'closure' is not subsettable
> 
> ggsave("tss_genomic_distribution_quantiles.png", plot = p, device = "png", type = "cairo", height = 4, width = 4)

**Comment by zentnerlab** [comment]
rename 'genomic_dist' to 'tss_distribution'

**Comment by rpolicastro** [comment]
[README has now been fixed](https://github.com/rpolicastro/tsrexplorer/commit/29e6fc2f80aa16ace48b6256aac0867ca22b9cf3#diff-04c6e90faac2675aa89e2176d2eec7d8R99)
