### ISSUE TITLE
Example average plot scaling

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#12]
p <- plot_average(exp, data_type = "tss", threshold = 3, ncol = 3) +
	theme(text = element_text(size = 6))

ggsave("tss_average_plot.png", plot = p, device = "png", type = "cairo", height = 0.5, width = 4)

The 0.5 height completely obscures the actual plot and only shows the sample name when I run it. Looks fine with a value of 1. Not a bug per se, but for improving the example code.

**Comment by rpolicastro** [comment]
[fixed](https://github.com/rpolicastro/tsrexplorer/commit/7040ebcf03535c3e676dd37c54dacf76171736b3#diff-04c6e90faac2675aa89e2176d2eec7d8L117), thanks!
