### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#17]
Prior to normalization, we should be able to set a counts threshold that will cut out any TSSs that do not meet that number of tags in any sample in the count matrix (3 in our case).

**Comment by rpolicastro** [comment]
The `count_normalization` function now has 2 more arguments, 'threshold' and 'n_samples'.

Positions, whether they be TSSs or TSRs, will be kept only if at least 'n_samples' have greater than or equal to 'threshold' number of reads.

https://github.com/rpolicastro/tsrexplorer/commit/b37a5cd09bc8af7f36261a63c8ee1603802a1638
