### ISSUE TITLE
Normalization

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#18]
Use normalized counts for any function requiring TSS signal (correlations, average plots, heat maps).

**Comment by rpolicastro** [comment]
Added argument 'normalized' to the function `annotate_features` that when TRUE will annotate based on the normalized (and potentially filtered) counts instead of the raw (and potentially filtered) counts.

https://github.com/rpolicastro/tsrexplorer/commit/d2fc5a74b9e9dbdbdb0f55cc7e2d917bfba36d55

**Comment by rpolicastro** [comment]
When you normalize the counts now, it outputs TMM and CPM normalized counts. Correlation plots will use TMM normalized counts, and many of the downstream functions have an argument use_cpm where you can use the cpm normalized counts (if it makes sense for that function).
