### ISSUE TITLE
# genes with TSRs plot

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#2]

**Comment by rpolicastro** [comment]
Added with [latest commit](https://github.com/rpolicastro/tsrexplorer/commit/cb8cd8d1b779e938d1848a31d6925be08d15cf55).

Documentation for TSSs is [here](https://github.com/rpolicastro/tsrexplorer#tss-feature-detection), and TSRs [here](https://github.com/rpolicastro/tsrexplorer#tsr-feature-detection).
