### ISSUE TITLE
Color of hierarchically clustered heatmap

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#20]
Integrate viridis (or an option to specify the color scale) into this feature.

**Comment by rpolicastro** [comment]
Set the default color pallet to viridis for now.

https://github.com/rpolicastro/tsrexplorer/commit/92cd426a9b251cd9466bb62cff555f1f343f35ff

**Comment by rpolicastro** [comment]
You can now pass any color palette. For example, to make it viridis you would add `col = viridis::viridis(100)`  to plot_correlation when 'hierarchical' is set.
