### ISSUE TITLE
Score column name in normalization of TSSs vs. TSRs

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#21]
`count_normalization` for TSSs requires a column titled 'score,' but looks for a column titled 'nTAGs' for TSRs.

**Comment by gzentner** [comment]
It seems now that TSR normalization looks for the nTAGs column name and replaces it with "score." However, TSS normalization still requires the column to be named "score," requiring a rename in reading in TSSs. I suggest making the normalization function replace "nTAGs" with "score" for TSSs as is now done for TSRs for uniformity and to reduce the amount of pre-processing needed when reading in TSSs.

**Comment by rpolicastro** [comment]
For TSSs and TSRs it should now just automatically add a score column if there is an nTAGs column, otherwise it will just use the existing score column.
