### ISSUE TITLE
TSS nTAGS handling

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#24]
Got this error with the latest pull when trying to normalize TSSs:

`exp <- count_normalization(exp, data_type = "tss", n_samples = 1, threshold = 3)
Error: `score` must evaluate to column positions or names, not a function`

**Comment by rpolicastro** [comment]
Seems to be fixed now as of the latest commit

https://github.com/rpolicastro/tsrexplorer/commit/286ca68978fed89cf01406b31de389de27e7bf73
