### ISSUE TITLE
Unknown columns in plot_tsr_metric

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#25]
Got the following error when attempting to plot TSR metrics:

```
> p <- plot_tsr_metric(exp, tsr_metrics = c("nTAGs", "nTSSs"), log2_transform = TRUE, ncol = 2) 
+     ggplot2::theme(text = element_text(size = 6))
Error: Unknown columns `nTAGs` and `nTSSs` 
```

**Comment by rpolicastro** [comment]
The example data is working fine for me. Does the TSR data have both the nTAGs and nTSSs column?

**Comment by gzentner** [comment]
It has all the proper columns, but I wonder if something else is up - it didn't work with the example data for me either.

**Comment by rpolicastro** [comment]
seems to have resolved itself
