### ISSUE TITLE
Ordering of quantile plots

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#26]
When specifying quantiles for plotting TSS distributions, the plots are ordered 5-1 (if quintiles are specified), which I believe is ranked high to low-scoring TSSs. However, in the quantile plot for TSS sequence logos, the plots are ranked 1-5. Would be good to have consistent ordering of plots between the two functions.

**Comment by rpolicastro** [comment]
Should be ordered 5-1 now with the latest commit

https://github.com/rpolicastro/tsrexplorer/commit/440e2ee0bfca835419bc47e091e49babe0b14997#diff-6cf92775a4b3a5a08a9f7f89d01032d0R119
