### ISSUE TITLE
feature_type unused in annotate_differential_tsrs in dev branch

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#27]
When attempting to run annotate_differential_tsrs with the edgeR output, I get:

`annotated_diff_tsrs <- annotate_differential_tsrs(diff_tsrs, annotation_file = annotation, feature_type = "transcript", upstream = 250, downstream = 100)
Error in annotate_differential_tsrs(diff_tsrs, annotation_file = annotation,  : 
  unused argument (feature_type = "transcript")`

Removal of the feature_type argument leads to: 
`Error in match.arg(level, c("transcript", "gene")) : 
  object 'feature_type' not found`

The documentation lists feature_type as an argument in annotate_differential_tsrs but it is not present in the usage example.

**Comment by rpolicastro** [comment]
Should be fixed with the latest ocmmit

https://github.com/rpolicastro/tsrexplorer/commit/3936eb8f27bae6cb6d116e1aef702e6f6577024e
