### ISSUE TITLE
NAs in human annotation

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#30]
A small fraction of annotations of human TSSs and TSRs is given as "NA," presumably due to there being an additional category in the Ensembl GTF.

**Comment by vpbrendel** [comment]
If this is derived from TSRexplore workflows, then this simply means that these sites are not located in the vicinity of a gene annotation (vicinity as set by the pupstream/pdownstream parameters in *wf1.Rscript).

**Comment by rpolicastro** [comment]
@vpbrendel I looked into it and it is something on my side. I fixed it with the latest commit.

https://github.com/rpolicastro/tsrexplorer/commit/9722e07bdb537e0a575a5f8d5a6a0cee6b26e14a
