### ISSUE TITLE
Reordering samples in plots

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#31]
In plots like the genomic distribution of TSSs/TSRs, the samples are given in alphabetical order. For instance, in the TSS dinucleotide frequency plot for human STRIPE-seq and CAGE TSSs, the order is "CAGE_10ug_1," "K562_100ng_1," "nanoCAGE_XL_7.5ug_1," "RAMPAGE_5ug_1." I think it would be useful to be able to specify an order of samples for plotting, so as to be able to have STRIPE-seq as the first sample in such plots.

**Comment by rpolicastro** [comment]
Should now be able to reorder the plots for genomic distribution and dinucleotide frequencies. Will add this to more plots in the future.

**Comment by rpolicastro** [comment]
Should work with all relevant functions in the development branch.
