### ISSUE TITLE
Error in explore_thresholds

### ISSUE THREAD

**Issue by gzentner** [rpolicastro/tsrexplorer#34]
I get the following error when running explore_thresholds:

`Error in score >= x : 
comparison (5) is possible only for atomic and list types`

**Comment by gzentner** [comment]
`thresh <- explore_thresholds(exp, annotation_file = annotation, feature_type = "transcript", max_threshold = 50, upstream = 250, downstream = 100, samples = stripe)`

**Comment by rpolicastro** [comment]
should be fixed as of the latest commit

https://github.com/rpolicastro/tsrexplorer/commit/55060834120898632c38496ce03ef1a89e047841
