### ISSUE TITLE
GO analysis

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#5]

**Comment by rpolicastro** [comment]
[Added function](https://github.com/rpolicastro/tsrexplorer/commit/6233f520ce60e811813efd9255216780309b2565) to export differential TSRs to a format amenable to clusterprofiler term enrichment.

Documentation [here](https://github.com/rpolicastro/tsrexplorer/commit/6233f520ce60e811813efd9255216780309b2565)
