### ISSUE TITLE
ggplot2 loading

### ISSUE THREAD

**Issue by zentnerlab** [rpolicastro/tsrexplorer#9]
ggplot2 must be manually loaded the first time the user wants to create a plot; any way to make it so that a module that requires ggplot2 loads it automatically?

**Comment by rpolicastro** [comment]
fixed vignettes in readme with [latest commit](https://github.com/rpolicastro/tsrexplorer/commit/8f6a61ffed3e3e0189e310efcb61e5f5cca2403f).
